import 'package:aetherlink_flutter/features/theming/application/default_theme_spec.dart';
import 'package:aetherlink_flutter/features/theming/domain/theme_preset.dart';
import 'package:aetherlink_flutter/features/theming/domain/theme_spec.dart';

/// The ten built-in theme presets shown in the 主题风格 selector, ported 1:1 from
/// `src/shared/config/themes.ts` `themeConfigs`.
///
/// Each preset reuses the shared typography / shape / density of
/// [defaultThemeSpec] (the original keeps font + radius theme-independent and
/// only swaps colors), so only the per-brightness color roles and the preview
/// gradient differ. Chat-bubble roles are not defined by `themes.ts`; they are
/// seeded palette-consistently (user bubble = the theme `primary`, AI bubble = a
/// neutral light tint / the dark surface) exactly as [defaultThemeSpec] does,
/// and remain user-overridable on the 信息气泡设置 page.
final List<ThemePreset> themePresets = [
  // The default preset reuses [defaultThemeSpec] verbatim so its (already
  // shipped) bubble roles are preserved.
  const ThemePreset(
    spec: defaultThemeSpec,
    description: '简洁现代的默认设计风格',
    gradientStart: 0xFF9333EA,
    gradientEnd: 0xFF754AB4,
  ),
  _preset(
    id: 'claude',
    name: 'Claude 风格',
    description: '温暖优雅的 Claude AI 设计风格',
    gradientStart: 0xFFD97706,
    gradientEnd: 0xFFEA580C,
    primary: 0xFFD97706,
    secondary: 0xFF059669,
    accent: 0xFFDC2626,
    backgroundLight: 0xFFFEF7ED,
    backgroundDark: 0xFF1C1917,
    surfaceLight: 0xFFFEF7ED,
    surfaceDark: 0xFF292524,
    textPrimaryLight: 0xFF1C1917,
    textPrimaryDark: 0xFFF5F5F4,
    textSecondaryLight: 0xFF78716C,
    textSecondaryDark: 0xFFA8A29E,
  ),
  _preset(
    id: 'nature',
    name: '自然风格',
    description: '2025年流行的自然系大地色调设计',
    gradientStart: 0xFF2D5016,
    gradientEnd: 0xFF5D6B47,
    primary: 0xFF2D5016,
    secondary: 0xFF8B7355,
    accent: 0xFFC7B299,
    backgroundLight: 0xFFF7F5F3,
    backgroundDark: 0xFF1A1F16,
    surfaceLight: 0xFFF7F5F3,
    surfaceDark: 0xFF252B20,
    textPrimaryLight: 0xFF1A1F16,
    textPrimaryDark: 0xFFE8E6E3,
    textSecondaryLight: 0xFF5D6B47,
    textSecondaryDark: 0xFFB8B5B0,
  ),
  _preset(
    id: 'tech',
    name: '未来科技',
    description: '2025年流行的科技感设计，冷色调与玻璃态效果',
    gradientStart: 0xFF3B82F6,
    gradientEnd: 0xFF8B5CF6,
    primary: 0xFF3B82F6,
    secondary: 0xFF8B5CF6,
    accent: 0xFF06B6D4,
    backgroundLight: 0xFFF8FAFC,
    backgroundDark: 0xFF0F172A,
    surfaceLight: 0xFFF8FAFC,
    surfaceDark: 0xFF1E293B,
    textPrimaryLight: 0xFF0F172A,
    textPrimaryDark: 0xFFF1F5F9,
    textSecondaryLight: 0xFF64748B,
    textSecondaryDark: 0xFF94A3B8,
  ),
  _preset(
    id: 'soft',
    name: '柔和渐变',
    description: '2025年流行的柔和渐变设计，温暖舒适的视觉体验',
    gradientStart: 0xFFEC4899,
    gradientEnd: 0xFFF472B6,
    primary: 0xFFEC4899,
    secondary: 0xFF14B8A6,
    accent: 0xFFF59E0B,
    backgroundLight: 0xFFFDF2F8,
    backgroundDark: 0xFF1F1626,
    surfaceLight: 0xFFFDF2F8,
    surfaceDark: 0xFF2D1B3D,
    textPrimaryLight: 0xFF1F1626,
    textPrimaryDark: 0xFFFCE7F3,
    textSecondaryLight: 0xFF9F1239,
    textSecondaryDark: 0xFFF9A8D4,
  ),
  _preset(
    id: 'ocean',
    name: '海洋风格',
    description: '2025年流行的海洋蓝绿色系，清新舒适的视觉体验',
    gradientStart: 0xFF0EA5E9,
    gradientEnd: 0xFF06B6D4,
    primary: 0xFF0EA5E9,
    secondary: 0xFF06B6D4,
    accent: 0xFF14B8A6,
    backgroundLight: 0xFFF0F9FF,
    backgroundDark: 0xFF0C1A2E,
    surfaceLight: 0xFFF0F9FF,
    surfaceDark: 0xFF1E3A5F,
    textPrimaryLight: 0xFF0C4A6E,
    textPrimaryDark: 0xFFE0F2FE,
    textSecondaryLight: 0xFF0369A1,
    textSecondaryDark: 0xFF7DD3FC,
  ),
  _preset(
    id: 'sunset',
    name: '日落风格',
    description: '2025年流行的日落色系，温暖浪漫的视觉氛围',
    gradientStart: 0xFFF97316,
    gradientEnd: 0xFFFB923C,
    primary: 0xFFF97316,
    secondary: 0xFFFB923C,
    accent: 0xFFFDE047,
    backgroundLight: 0xFFFFF7ED,
    backgroundDark: 0xFF1C1917,
    surfaceLight: 0xFFFFF7ED,
    surfaceDark: 0xFF292524,
    textPrimaryLight: 0xFF7C2D12,
    textPrimaryDark: 0xFFFED7AA,
    textSecondaryLight: 0xFFC2410C,
    textSecondaryDark: 0xFFFDBA74,
  ),
  _preset(
    id: 'cinnamonSlate',
    name: '肉桂板岩',
    description: '2025年流行趋势：深邃温暖的色调，带来内心的平静',
    gradientStart: 0xFF8B6F5C,
    gradientEnd: 0xFFB08968,
    primary: 0xFF8B6F5C,
    secondary: 0xFF5D4E4A,
    accent: 0xFFB08968,
    backgroundLight: 0xFFF5F1ED,
    backgroundDark: 0xFF1A1614,
    surfaceLight: 0xFFF5F1ED,
    surfaceDark: 0xFF2B2420,
    textPrimaryLight: 0xFF2B2420,
    textPrimaryDark: 0xFFF0EBE3,
    textSecondaryLight: 0xFF5D4E4A,
    textSecondaryDark: 0xFFC4B5A8,
  ),
  _preset(
    id: 'horizonGreen',
    name: '地平线绿',
    description: '2025年日本代表色：带蓝调的绿色，象征希望与自然',
    gradientStart: 0xFF4A9B8E,
    gradientEnd: 0xFF70B8A8,
    primary: 0xFF4A9B8E,
    secondary: 0xFF70B8A8,
    accent: 0xFF95D5C8,
    backgroundLight: 0xFFF5FAF8,
    backgroundDark: 0xFF0F1B18,
    surfaceLight: 0xFFF5FAF8,
    surfaceDark: 0xFF1A2B26,
    textPrimaryLight: 0xFF0F3D34,
    textPrimaryDark: 0xFFE8F5F1,
    textSecondaryLight: 0xFF2D6B5E,
    textSecondaryDark: 0xFFA8D5C8,
  ),
  _preset(
    id: 'cherryCoded',
    name: '樱桃编码',
    description: '2025年流行趋势：深樱桃红色，传达热情与活力',
    gradientStart: 0xFFC41E3A,
    gradientEnd: 0xFFE63E6D,
    primary: 0xFFC41E3A,
    secondary: 0xFFE63E6D,
    accent: 0xFFFF6B9D,
    backgroundLight: 0xFFFFF5F7,
    backgroundDark: 0xFF1A0C0F,
    surfaceLight: 0xFFFFF5F7,
    surfaceDark: 0xFF2B1418,
    textPrimaryLight: 0xFF450A0F,
    textPrimaryDark: 0xFFFFE8ED,
    textSecondaryLight: 0xFF78121C,
    textSecondaryDark: 0xFFFFB3C6,
  ),
];

/// The presets keyed by [ThemePreset.id] for O(1) lookup on selection / restore.
final Map<String, ThemePreset> themePresetsById = {
  for (final preset in themePresets) preset.id: preset,
};

/// The [ThemeSpec] for the style [id], falling back to the default theme for an
/// unknown id (mirrors the original `getValidThemeStyle`).
ThemeSpec themeSpecForStyle(String id) =>
    (themePresetsById[id] ?? themePresetsById['default']!).spec;

/// Builds a colored preset that shares the default theme's typography / shape /
/// density and seeds chat-bubble roles palette-consistently (see file doc).
ThemePreset _preset({
  required String id,
  required String name,
  required String description,
  required int gradientStart,
  required int gradientEnd,
  required int primary,
  required int secondary,
  required int accent,
  required int backgroundLight,
  required int backgroundDark,
  required int surfaceLight,
  required int surfaceDark,
  required int textPrimaryLight,
  required int textPrimaryDark,
  required int textSecondaryLight,
  required int textSecondaryDark,
}) {
  const neutralAiBubbleLight = 0xFFF1F5F9;
  return ThemePreset(
    spec: ThemeSpec(
      id: id,
      name: name,
      colors: ThemeColors(
        light: ColorRoleSet(
          primary: primary,
          secondary: secondary,
          accent: accent,
          background: backgroundLight,
          surface: surfaceLight,
          textPrimary: textPrimaryLight,
          textSecondary: textSecondaryLight,
          bubbleUser: primary,
          bubbleAi: neutralAiBubbleLight,
        ),
        dark: ColorRoleSet(
          primary: primary,
          secondary: secondary,
          accent: accent,
          background: backgroundDark,
          surface: surfaceDark,
          textPrimary: textPrimaryDark,
          textSecondary: textSecondaryDark,
          bubbleUser: primary,
          bubbleAi: surfaceDark,
        ),
      ),
      typography: const ThemeTypography(fontFamily: 'Roboto'),
      shape: const ThemeShape(),
      density: ThemeDensity.standard,
    ),
    description: description,
    gradientStart: gradientStart,
    gradientEnd: gradientEnd,
  );
}
