import 'dart:convert';
import 'dart:io';

import 'package:archive/archive.dart';

import 'package:aetherlink_flutter/core/database/app_database.dart';
import 'package:aetherlink_flutter/core/utils/id_generator.dart';
import 'package:aetherlink_flutter/features/backup/domain/backup_config.dart';
import 'package:aetherlink_flutter/features/chat/data/message_tree_backfill.dart';
import 'package:aetherlink_flutter/features/chat/domain/entities/message.dart';
import 'package:aetherlink_flutter/features/chat/domain/entities/message_block.dart';
import 'package:aetherlink_flutter/features/chat/domain/entities/message_block_status.dart';
import 'package:aetherlink_flutter/features/chat/domain/entities/message_role.dart';
import 'package:aetherlink_flutter/features/chat/domain/entities/message_status.dart';
import 'package:aetherlink_flutter/shared/domain/assistant.dart';
import 'package:aetherlink_flutter/shared/domain/model.dart';
import 'package:aetherlink_flutter/shared/domain/model_detection/model_enricher.dart';
import 'package:aetherlink_flutter/shared/domain/model_provider.dart';
import 'package:aetherlink_flutter/shared/domain/topic.dart';

/// Result of a Cherry Studio data import.
class CherryImportResult {
  final int providers;
  final int conversations;
  final int messages;
  final int assistants;
  final int models;
  final List<String> warnings;

  const CherryImportResult({
    required this.providers,
    required this.conversations,
    required this.messages,
    this.assistants = 0,
    this.models = 0,
    this.warnings = const [],
  });
}

/// Imports data from Cherry Studio backup format (.zip/.bak/.json) into the
/// app database.
///
/// Supports two backup formats:
///
/// **Legacy JSON format (version ≤ 5)** — generated by Cherry Studio's
/// "Export to phone" / LAN Transfer feature:
/// ```json
/// {
///   "version": 5,
///   "localStorage": { "persist:cherry-studio": "..." },
///   "indexedDB": { "topics": [...], "files": [...], "message_blocks": [...] }
/// }
/// ```
///
/// **Direct Backup format (version 6+)** — generated by Cherry Studio's
/// standard backup button. Contains raw Chromium IndexedDB/LocalStorage binary
/// files + a `metadata.json`. This format is NOT directly parseable without a
/// LevelDB reader; we detect it and provide a clear error message guiding
/// the user to export using the LAN Transfer format instead.
class CherryImporter {
  CherryImporter._();

  /// Import from a Cherry Studio backup file.
  static Future<CherryImportResult> import({
    required File file,
    required RestoreMode mode,
    required AppDatabase db,
  }) async {
    final root = await _readCherryBackupFile(file);

    // Parse localStorage persist data
    final localStorage =
        (root['localStorage'] as Map?)?.map(
          (k, v) => MapEntry(k.toString(), v),
        ) ??
        const <String, dynamic>{};
    final persistStr = (localStorage['persist:cherry-studio'] ?? '') as String;
    if (persistStr.isEmpty) {
      throw Exception('缺少 Cherry Studio 持久化数据（persist:cherry-studio）');
    }

    late Map<String, dynamic> persistObj;
    try {
      persistObj = jsonDecode(persistStr) as Map<String, dynamic>;
    } catch (_) {
      throw Exception('无效的 Cherry Studio 持久化数据');
    }

    // Parse slices from persist (each slice is a nested JSON string)
    final llmSlice = _parseSlice(persistObj, 'llm');
    final assistantsSlice = _parseSlice(persistObj, 'assistants');

    // Extract providers with models
    final List<dynamic> cherryProviders =
        (llmSlice['providers'] as List?) ?? const <dynamic>[];

    // Extract assistants
    final List<dynamic> cherryAssistants =
        (assistantsSlice['assistants'] as List?) ?? const <dynamic>[];

    // Parse IndexedDB
    final indexedDB =
        (root['indexedDB'] as Map?)?.map((k, v) => MapEntry(k.toString(), v)) ??
        const <String, dynamic>{};
    final List<dynamic> cherryTopicsWithMessages =
        (indexedDB['topics'] as List?) ?? const <dynamic>[];
    final List<dynamic> cherryMessageBlocks =
        (indexedDB['message_blocks'] as List?) ?? const <dynamic>[];

    // Build assistant id -> assistant data map
    final Map<String, Map<String, dynamic>> assistantMap = {};
    for (final a in cherryAssistants) {
      if (a is! Map) continue;
      final id = (a['id'] ?? '').toString();
      if (id.isEmpty) continue;
      assistantMap[id] = a.map((k, v) => MapEntry(k.toString(), v));
    }

    // Build topic metadata from assistants[].topics[] and map topicId -> assistantId
    final Map<String, Map<String, dynamic>> topicMeta = {};
    final Map<String, String> topicToAssistant = {};
    for (final a in cherryAssistants) {
      if (a is! Map) continue;
      final assistantId = (a['id'] ?? '').toString();
      final topics = (a['topics'] as List?) ?? const <dynamic>[];
      for (final t in topics) {
        if (t is Map && t['id'] != null) {
          final topicId = t['id'].toString();
          topicMeta[topicId] = t.map((k, v) => MapEntry(k.toString(), v));
          if (assistantId.isNotEmpty) {
            topicToAssistant[topicId] = assistantId;
          }
        }
      }
    }

    // Build topicId -> messages map from IndexedDB topics
    final Map<String, List<Map<String, dynamic>>> topicMessages = {};
    for (final e in cherryTopicsWithMessages) {
      if (e is! Map) continue;
      final id = (e['id'] ?? '').toString();
      if (id.isEmpty) continue;
      final msgs = (e['messages'] as List?) ?? const <dynamic>[];
      topicMessages[id] = [
        for (final m in msgs)
          if (m is Map) m.map((k, v) => MapEntry(k.toString(), v)),
      ];
    }

    // Build messageId -> list of block data from message_blocks table
    final Map<String, List<Map<String, dynamic>>> blocksByMessageId = {};
    for (final b in cherryMessageBlocks) {
      if (b is! Map) continue;
      final messageId = (b['messageId'] ?? '').toString();
      if (messageId.isEmpty) continue;
      final blockMap = b.map((k, v) => MapEntry(k.toString(), v));
      blocksByMessageId.putIfAbsent(messageId, () => []).add(blockMap);
    }

    // Build messageId -> reconstructed text (for fallback when no block can be
    // created natively)
    final Map<String, String> blockTextByMessageId = {};
    for (final entry in blocksByMessageId.entries) {
      final parts = <String>[];
      for (final b in entry.value) {
        final text = _blockToText(b);
        if (text != null && text.isNotEmpty) parts.add(text);
      }
      if (parts.isNotEmpty) {
        blockTextByMessageId[entry.key] = parts.join('\n');
      }
    }

    final warnings = <String>[];

    return db.transaction(() async {
      if (mode == RestoreMode.overwrite) {
        await db.delete(db.messageBlockRows).go();
        await db.delete(db.messageRows).go();
        await db.delete(db.topicRows).go();
        await db.delete(db.providerRows).go();
        await db.delete(db.assistantRows).go();
      }

      // Import providers (with models)
      final providerResult =
          await _importProviders(cherryProviders, mode, db);

      // Import assistants
      final assistantCount =
          await _importAssistants(assistantMap, mode, db);

      // Import conversations
      final convResult = await _importConversations(
        topicMeta: topicMeta,
        topicMessages: topicMessages,
        topicToAssistant: topicToAssistant,
        blocksByMessageId: blocksByMessageId,
        blockTexts: blockTextByMessageId,
        mode: mode,
        db: db,
        warnings: warnings,
      );

      return CherryImportResult(
        providers: providerResult.providerCount,
        models: providerResult.modelCount,
        conversations: convResult.conversations,
        messages: convResult.messages,
        assistants: assistantCount,
        warnings: warnings,
      );
    });
  }

  // ---------------------------------------------------------------------------
  // Slice parsing helper
  // ---------------------------------------------------------------------------

  static Map<String, dynamic> _parseSlice(
    Map<String, dynamic> persistObj,
    String key,
  ) {
    try {
      final str = (persistObj[key] ?? '') as String;
      if (str.isNotEmpty) return jsonDecode(str) as Map<String, dynamic>;
    } catch (_) {}
    return const {};
  }

  // ---------------------------------------------------------------------------
  // File reading (ZIP / plain JSON / GZIP) with v6+ detection
  // ---------------------------------------------------------------------------

  static Future<Map<String, dynamic>> _readCherryBackupFile(File file) async {
    final bytes = await file.readAsBytes();

    Map<String, dynamic>? tryParse(String text) {
      try {
        final obj = jsonDecode(text) as Map<String, dynamic>;
        if (obj.containsKey('localStorage') && obj.containsKey('indexedDB')) {
          return obj;
        }
      } catch (_) {}
      return null;
    }

    // 1) Plain JSON
    try {
      final content = utf8.decode(bytes, allowMalformed: true);
      final obj = tryParse(content);
      if (obj != null) return obj;
    } catch (_) {}

    // 2) ZIP archive
    try {
      final archive = ZipDecoder().decodeBytes(bytes);

      // Check for v6+ direct backup format (contains metadata.json)
      final hasMetadata = archive.any(
        (entry) =>
            entry.isFile &&
            (entry.name == 'metadata.json' ||
                entry.name.endsWith('/metadata.json')),
      );
      if (hasMetadata) {
        // Check if it's really a Cherry Studio direct backup
        for (final entry in archive) {
          if (!entry.isFile) continue;
          if (entry.name == 'metadata.json' ||
              entry.name.endsWith('/metadata.json')) {
            try {
              final metaStr = utf8.decode(
                entry.content as List<int>,
                allowMalformed: true,
              );
              final meta = jsonDecode(metaStr) as Map<String, dynamic>;
              if (meta['appName'] == 'Cherry Studio' &&
                  (meta['version'] as num? ?? 0) >= 6) {
                throw Exception(
                  '此备份文件是 Cherry Studio v6+ 直接备份格式（包含原始数据库二进制文件），'
                  '本应用无法直接解析。\n\n'
                  '请在 Cherry Studio 中使用「设置 → 数据 → 导出到手机」功能重新导出，'
                  '该方式会生成兼容的 JSON 格式备份文件。',
                );
              }
            } catch (e) {
              if (e is Exception &&
                  e.toString().contains('Cherry Studio v6+')) {
                rethrow;
              }
            }
          }
        }
      }

      // Try to find legacy data.json or a top-level JSON with the expected keys
      for (final entry in archive) {
        if (!entry.isFile) continue;
        // Prefer data.json (legacy backup format in ZIP)
        if (entry.name == 'data.json' || entry.name.endsWith('/data.json')) {
          try {
            final content = utf8.decode(
              entry.content as List<int>,
              allowMalformed: true,
            );
            final obj = tryParse(content);
            if (obj != null) return obj;
          } catch (_) {}
        }
      }

      // Fallback: try all JSON-like files in the archive
      for (final entry in archive) {
        if (!entry.isFile) continue;
        if (entry.size > 500 * 1024 * 1024) continue; // skip >500MB files
        try {
          final content = utf8.decode(
            entry.content as List<int>,
            allowMalformed: true,
          );
          final obj = tryParse(content);
          if (obj != null) return obj;
        } catch (_) {}
      }
    } catch (e) {
      // Rethrow our own descriptive exceptions
      if (e is Exception && e.toString().contains('Cherry Studio v6+')) {
        rethrow;
      }
    }

    // 3) GZIP
    try {
      final gunzipped = GZipDecoder().decodeBytes(bytes);
      final content = utf8.decode(gunzipped, allowMalformed: true);
      final obj = tryParse(content);
      if (obj != null) return obj;
    } catch (_) {}

    throw Exception(
      '无法解析 Cherry Studio 备份文件。\n\n'
      '支持的格式：\n'
      '• Cherry Studio「导出到手机」生成的 JSON/ZIP 文件\n'
      '• Cherry Studio 旧版（v1.8 以前）备份的 .bak/.zip 文件\n\n'
      '如果您使用的是 Cherry Studio 新版（v1.9+）的标准备份功能，'
      '请改用「设置 → 数据 → 导出到手机」导出。',
    );
  }

  // ---------------------------------------------------------------------------
  // Block text extraction (for fallback)
  // ---------------------------------------------------------------------------

  static String? _blockToText(Map<String, dynamic> b) {
    final type = (b['type'] ?? '').toString();
    final content = (b['content'] ?? '').toString();

    switch (type) {
      case 'main_text':
        return content;
      case 'thinking':
        if (content.isNotEmpty) return '<think>\n$content\n</think>';
        return null;
      case 'code':
        final lang = (b['language'] ?? '').toString();
        if (content.isNotEmpty) return '```$lang\n$content\n```';
        return null;
      case 'image':
        final url = (b['url'] ?? '').toString();
        if (url.isNotEmpty) return '![image]($url)';
        return '[图片]';
      case 'file':
        final fileName =
            (b['file'] is Map ? b['file']['name'] : null)?.toString() ?? '';
        return fileName.isNotEmpty ? '[文件: $fileName]' : '[文件]';
      case 'tool':
        final toolName = (b['toolName'] ?? b['toolId'] ?? '').toString();
        final toolContent = content.isNotEmpty ? content : '';
        if (toolName.isNotEmpty) {
          return toolContent.isNotEmpty
              ? '[工具调用: $toolName]\n$toolContent'
              : '[工具调用: $toolName]';
        }
        return toolContent.isNotEmpty ? '[工具调用]\n$toolContent' : null;
      case 'citation':
        return content.isNotEmpty ? content : null;
      case 'translation':
        return content.isNotEmpty ? content : null;
      case 'video':
        final url = (b['url'] ?? '').toString();
        if (url.isNotEmpty) return '[视频: $url]';
        return '[视频]';
      case 'compact':
        return content.isNotEmpty ? content : null;
      case 'error':
        final msg = (b['message'] ?? content).toString();
        return msg.isNotEmpty ? '[错误: $msg]' : null;
      default:
        return content.isNotEmpty ? content : null;
    }
  }

  // ---------------------------------------------------------------------------
  // Providers (with models)
  // ---------------------------------------------------------------------------

  static Future<({int providerCount, int modelCount})> _importProviders(
    List<dynamic> cherryProviders,
    RestoreMode mode,
    AppDatabase db,
  ) async {
    int providerCount = 0;
    int modelCount = 0;

    for (final p in cherryProviders) {
      if (p is! Map) continue;
      final id = (p['id'] ?? '').toString();
      if (id.isEmpty) continue;

      if (mode == RestoreMode.merge) {
        final existing = await db.providerDao.getById(id);
        if (existing != null) continue;
      }

      final type = (p['type'] ?? '').toString().toLowerCase();
      final name = (p['name'] ?? id).toString();
      final apiKey = (p['apiKey'] ?? '').toString().split(',').first.trim();
      final apiHost = (p['apiHost'] ?? '').toString().trim();

      String baseUrl = apiHost;
      if (baseUrl.isEmpty) {
        baseUrl = _defaultBaseUrlForType(type);
      } else if (baseUrl.endsWith('/')) {
        baseUrl = baseUrl.substring(0, baseUrl.length - 1);
      }

      final providerType = _mapProviderType(type);

      // Extract models from provider
      final List<Model> models = [];
      final cherryModels = (p['models'] as List?) ?? const <dynamic>[];
      for (final m in cherryModels) {
        if (m is! Map) continue;
        final modelId = (m['id'] ?? '').toString();
        final modelName = (m['name'] ?? modelId).toString();
        if (modelId.isEmpty) continue;
        models.add(Model(
          id: modelId,
          name: modelName,
          provider: id,
        ));
        modelCount++;
      }

      // Populate capabilities once at import time (preset registry → regex
      // inference) so runtime checks can read the field.
      final enrichedModels = await enrichModels(models);

      final provider = ModelProvider(
        id: id,
        name: name,
        avatar: name.isNotEmpty ? name.substring(0, 1).toUpperCase() : 'P',
        color: '#10a37f',
        isEnabled: apiKey.isNotEmpty,
        apiKey: apiKey.isNotEmpty ? apiKey : null,
        baseUrl: baseUrl,
        providerType: providerType,
        models: enrichedModels,
      );

      try {
        await db.providerDao.upsert(provider);
        providerCount++;
      } catch (_) {}
    }
    return (providerCount: providerCount, modelCount: modelCount);
  }

  /// Maps Cherry Studio provider type string to a normalized type.
  static String _mapProviderType(String type) {
    switch (type) {
      case 'anthropic':
        return 'anthropic';
      case 'gemini':
        return 'gemini';
      case 'azure-openai':
        return 'azure-openai';
      case 'ollama':
        return 'ollama';
      case 'openai-response':
      case 'openai':
        return 'openai';
      case 'mistral':
        return 'mistral';
      case 'vertexai':
      case 'vertex-anthropic':
        return 'vertexai';
      case 'aws-bedrock':
        return 'aws-bedrock';
      case 'new-api':
      case 'gateway':
        return 'openai'; // compatible API, treat as openai
      default:
        return 'openai';
    }
  }

  /// Returns a sensible default base URL given the provider type.
  static String _defaultBaseUrlForType(String type) {
    switch (type) {
      case 'anthropic':
        return 'https://api.anthropic.com';
      case 'gemini':
        return 'https://generativelanguage.googleapis.com';
      case 'mistral':
        return 'https://api.mistral.ai/v1';
      case 'ollama':
        return 'http://localhost:11434';
      default:
        return 'https://api.openai.com/v1';
    }
  }

  // ---------------------------------------------------------------------------
  // Assistants
  // ---------------------------------------------------------------------------

  static Future<int> _importAssistants(
    Map<String, Map<String, dynamic>> assistantMap,
    RestoreMode mode,
    AppDatabase db,
  ) async {
    int count = 0;
    for (final entry in assistantMap.entries) {
      final id = entry.key;
      final a = entry.value;

      if (mode == RestoreMode.merge) {
        final existing = await db.assistantDao.getById(id);
        if (existing != null) continue;
      }

      final name = (a['name'] ?? '').toString();
      if (name.isEmpty) continue;

      final prompt = (a['prompt'] ?? '').toString();
      final description = (a['description'] ?? '').toString();
      final emoji = (a['emoji'] ?? '').toString();
      final type = (a['type'] ?? '').toString();

      // Extract topic IDs from this assistant
      final topics = (a['topics'] as List?) ?? const <dynamic>[];
      final topicIds = <String>[];
      for (final t in topics) {
        if (t is Map && t['id'] != null) {
          topicIds.add(t['id'].toString());
        }
      }

      // Extract model info
      String? modelId;
      final defaultModel = a['defaultModel'] ?? a['model'];
      if (defaultModel is Map) {
        modelId = (defaultModel['id'] ?? '').toString();
        if (modelId.isEmpty) modelId = null;
      }

      // Extract settings
      double? temperature;
      int? maxTokens;
      int? maxMessagesInContext;
      final settings = a['settings'];
      if (settings is Map) {
        temperature = _parseDouble(settings['temperature']);
        maxTokens = _parseInt(settings['maxTokens']);
        maxMessagesInContext = _parseInt(settings['contextCount']);
      }

      final now = DateTime.now();
      final createdAtStr = (a['createdAt'] ?? '').toString();
      final createdAt = DateTime.tryParse(createdAtStr) ?? now;

      final assistant = Assistant(
        id: id,
        name: name,
        description: description.isNotEmpty ? description : null,
        emoji: emoji.isNotEmpty ? emoji : null,
        systemPrompt: prompt.isNotEmpty ? prompt : null,
        model: modelId,
        temperature: temperature,
        maxTokens: maxTokens,
        maxMessagesInContext: maxMessagesInContext,
        type: type.isNotEmpty ? type : null,
        topicIds: topicIds,
        createdAt: createdAt,
        updatedAt: createdAt,
      );

      try {
        await db.assistantDao.upsert(assistant);
        count++;
      } catch (_) {}
    }
    return count;
  }

  // ---------------------------------------------------------------------------
  // Conversations (topics + messages + blocks)
  // ---------------------------------------------------------------------------

  static Future<({int conversations, int messages})> _importConversations({
    required Map<String, Map<String, dynamic>> topicMeta,
    required Map<String, List<Map<String, dynamic>>> topicMessages,
    required Map<String, String> topicToAssistant,
    required Map<String, List<Map<String, dynamic>>> blocksByMessageId,
    required Map<String, String> blockTexts,
    required RestoreMode mode,
    required AppDatabase db,
    required List<String> warnings,
  }) async {
    int convCount = 0;
    int msgCount = 0;

    for (final entry in topicMessages.entries) {
      final topicId = entry.key;
      final messages = entry.value;
      if (messages.isEmpty) continue;

      final meta = topicMeta[topicId] ?? const {};
      final title = (meta['name'] ?? '').toString();
      final createdAtStr = (meta['createdAt'] ?? '').toString();
      final updatedAtStr = (meta['updatedAt'] ?? createdAtStr).toString();
      final createdAt = DateTime.tryParse(createdAtStr) ?? DateTime.now();
      final updatedAt = DateTime.tryParse(updatedAtStr) ?? createdAt;

      // Resolve assistant association
      final assistantId = topicToAssistant[topicId] ?? 'default';

      final newTopicId = generateId('topic');
      final messageIds = <String>[];

      for (final msg in messages) {
        final role = (msg['role'] ?? '').toString().toLowerCase();
        final messageRole = _parseRole(role);
        if (messageRole == null) continue;

        final cherryMsgId = (msg['id'] ?? '').toString();
        final msgCreatedAtStr = (msg['createdAt'] ?? '').toString();
        final msgCreatedAt = DateTime.tryParse(msgCreatedAtStr) ?? createdAt;
        final msgId = generateId('msg');

        // Try to import blocks natively from message_blocks table
        final rawBlocks = cherryMsgId.isNotEmpty
            ? (blocksByMessageId[cherryMsgId] ?? const [])
            : const <Map<String, dynamic>>[];

        final importedBlockIds = <String>[];

        if (rawBlocks.isNotEmpty) {
          // Import each block with proper typing
          for (final rawBlock in rawBlocks) {
            final block = _convertBlock(
              rawBlock: rawBlock,
              messageId: msgId,
              createdAt: msgCreatedAt,
            );
            if (block != null) {
              await db.messageBlockDao.upsert(block);
              importedBlockIds.add(block.id);
            }
          }
        }

        // If no blocks were imported from the table, try direct content or
        // reconstructed text
        if (importedBlockIds.isEmpty) {
          var content = (msg['content'] ?? '').toString();
          if (content.isEmpty && cherryMsgId.isNotEmpty) {
            content = blockTexts[cherryMsgId] ?? '';
          }
          if (content.isEmpty) continue;

          final blockId = generateId('block');
          final block = MessageBlock.mainText(
            id: blockId,
            messageId: msgId,
            status: MessageBlockStatus.success,
            createdAt: msgCreatedAt,
            content: content,
          );
          await db.messageBlockDao.upsert(block);
          importedBlockIds.add(blockId);
        }

        final message = Message(
          id: msgId,
          role: messageRole,
          assistantId: assistantId,
          topicId: newTopicId,
          createdAt: msgCreatedAt,
          status: MessageStatus.success,
          blocks: importedBlockIds,
        );
        await db.messageDao.upsert(message);
        messageIds.add(msgId);
        msgCount++;
      }

      if (messageIds.isEmpty) continue;

      final topic = Topic(
        id: newTopicId,
        assistantId: assistantId,
        name: title.isNotEmpty ? title : '导入的对话',
        createdAt: createdAt,
        updatedAt: updatedAt,
        messageIds: messageIds,
        messageCount: messageIds.length,
      );
      await db.topicDao.upsert(topic);
      // Link the flat imported messages into the tree shape (virtual root +
      // parentId + activeNodeId) so the branch graph and active path are
      // correct; without this every node is an orphan root.
      await linkTopicMessageTree(db, topic);
      convCount++;
    }

    return (conversations: convCount, messages: msgCount);
  }

  // ---------------------------------------------------------------------------
  // Block conversion — maps Cherry Studio MessageBlock to Flutter MessageBlock
  // ---------------------------------------------------------------------------

  static MessageBlock? _convertBlock({
    required Map<String, dynamic> rawBlock,
    required String messageId,
    required DateTime createdAt,
  }) {
    final type = (rawBlock['type'] ?? '').toString();
    final blockId = generateId('block');
    final blockCreatedAtStr = (rawBlock['createdAt'] ?? '').toString();
    final blockCreatedAt = DateTime.tryParse(blockCreatedAtStr) ?? createdAt;

    switch (type) {
      case 'main_text':
        final content = (rawBlock['content'] ?? '').toString();
        if (content.isEmpty) return null;
        return MessageBlock.mainText(
          id: blockId,
          messageId: messageId,
          status: MessageBlockStatus.success,
          createdAt: blockCreatedAt,
          content: content,
        );

      case 'thinking':
        final content = (rawBlock['content'] ?? '').toString();
        if (content.isEmpty) return null;
        final thinkingMs = _parseInt(rawBlock['thinking_millsec']);
        return MessageBlock.thinking(
          id: blockId,
          messageId: messageId,
          status: MessageBlockStatus.success,
          createdAt: blockCreatedAt,
          content: content,
          thinkingMillsec: thinkingMs,
        );

      case 'code':
        final content = (rawBlock['content'] ?? '').toString();
        if (content.isEmpty) return null;
        final language = (rawBlock['language'] ?? '').toString();
        return MessageBlock.code(
          id: blockId,
          messageId: messageId,
          status: MessageBlockStatus.success,
          createdAt: blockCreatedAt,
          content: content,
          language: language.isNotEmpty ? language : null,
        );

      case 'image':
        final url = (rawBlock['url'] ?? '').toString();
        // If no URL, skip (we can't import binary image data)
        if (url.isEmpty) return null;
        return MessageBlock.image(
          id: blockId,
          messageId: messageId,
          status: MessageBlockStatus.success,
          createdAt: blockCreatedAt,
          url: url,
          mimeType: 'image/png',
        );

      case 'video':
        final url = (rawBlock['url'] ?? rawBlock['filePath'] ?? '').toString();
        if (url.isEmpty) return null;
        return MessageBlock.video(
          id: blockId,
          messageId: messageId,
          status: MessageBlockStatus.success,
          createdAt: blockCreatedAt,
          url: url,
          mimeType: 'video/mp4',
        );

      case 'tool':
        final toolId = (rawBlock['toolId'] ?? '').toString();
        final toolName = (rawBlock['toolName'] ?? '').toString();
        if (toolId.isEmpty && toolName.isEmpty) return null;
        final arguments = rawBlock['arguments'] is Map
            ? Map<String, dynamic>.from(rawBlock['arguments'] as Map)
            : null;
        final content = rawBlock['content'];
        return MessageBlock.tool(
          id: blockId,
          messageId: messageId,
          status: MessageBlockStatus.success,
          createdAt: blockCreatedAt,
          toolId: toolId.isNotEmpty ? toolId : toolName,
          toolName: toolName.isNotEmpty ? toolName : null,
          arguments: arguments,
          content: content,
        );

      case 'file':
        final fileData = rawBlock['file'];
        String fileName = '';
        String fileUrl = '';
        String mimeType = '';
        if (fileData is Map) {
          fileName = (fileData['name'] ?? fileData['origin_name'] ?? '')
              .toString();
          fileUrl = (fileData['path'] ?? fileData['url'] ?? '').toString();
          mimeType = (fileData['type'] ?? '').toString();
        }
        if (fileName.isEmpty && fileUrl.isEmpty) return null;
        return MessageBlock.file(
          id: blockId,
          messageId: messageId,
          status: MessageBlockStatus.success,
          createdAt: blockCreatedAt,
          name: fileName.isNotEmpty ? fileName : 'file',
          url: fileUrl,
          mimeType: mimeType.isNotEmpty ? mimeType : 'application/octet-stream',
        );

      case 'citation':
        // Cherry Studio citation blocks contain web search response data
        final content = (rawBlock['content'] ?? '').toString();
        return MessageBlock.citation(
          id: blockId,
          messageId: messageId,
          status: MessageBlockStatus.success,
          createdAt: blockCreatedAt,
          content: content,
          response: rawBlock['response'],
        );

      case 'translation':
        final content = (rawBlock['content'] ?? '').toString();
        if (content.isEmpty) return null;
        final sourceBlockId = (rawBlock['sourceBlockId'] ?? '').toString();
        final sourceLanguage =
            (rawBlock['sourceLanguage'] ?? '').toString();
        final targetLanguage =
            (rawBlock['targetLanguage'] ?? '').toString();
        return MessageBlock.translation(
          id: blockId,
          messageId: messageId,
          status: MessageBlockStatus.success,
          createdAt: blockCreatedAt,
          content: content,
          sourceContent: '', // Not available in Cherry Studio backup
          sourceLanguage:
              sourceLanguage.isNotEmpty ? sourceLanguage : 'unknown',
          targetLanguage:
              targetLanguage.isNotEmpty ? targetLanguage : 'unknown',
          sourceBlockId: sourceBlockId.isNotEmpty ? sourceBlockId : null,
        );

      case 'error':
        final content = (rawBlock['content'] ?? '').toString();
        final errorData = rawBlock['error'];
        String? errorMessage;
        if (errorData is Map) {
          errorMessage = (errorData['message'] ?? '').toString();
        }
        return MessageBlock.error(
          id: blockId,
          messageId: messageId,
          status: MessageBlockStatus.error,
          createdAt: blockCreatedAt,
          content: content.isNotEmpty
              ? content
              : (errorMessage ?? 'Unknown error'),
          message: errorMessage,
        );

      case 'compact':
        // Compact blocks are /compact command responses
        final content = (rawBlock['content'] ?? '').toString();
        if (content.isEmpty) return null;
        // Store as main_text since Flutter doesn't have a compact block type
        // that matches exactly — but the content is still useful.
        return MessageBlock.mainText(
          id: blockId,
          messageId: messageId,
          status: MessageBlockStatus.success,
          createdAt: blockCreatedAt,
          content: content,
        );

      default:
        // For unknown block types, try to extract content as main_text
        final content = (rawBlock['content'] ?? '').toString();
        if (content.isEmpty) return null;
        return MessageBlock.mainText(
          id: blockId,
          messageId: messageId,
          status: MessageBlockStatus.success,
          createdAt: blockCreatedAt,
          content: content,
        );
    }
  }

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------

  static MessageRole? _parseRole(String role) {
    switch (role) {
      case 'user':
        return MessageRole.user;
      case 'assistant':
        return MessageRole.assistant;
      case 'system':
        return MessageRole.system;
      default:
        return null;
    }
  }

  static double? _parseDouble(dynamic value) {
    if (value == null) return null;
    if (value is double) return value;
    if (value is int) return value.toDouble();
    final str = value.toString();
    return double.tryParse(str);
  }

  static int? _parseInt(dynamic value) {
    if (value == null) return null;
    if (value is int) return value;
    if (value is double) return value.toInt();
    final str = value.toString();
    return int.tryParse(str);
  }
}
