// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'tts_provider_setting.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_TtsProviderSetting _$TtsProviderSettingFromJson(
  Map<String, dynamic> json,
) => _TtsProviderSetting(
  id: json['id'] as String,
  kind: $enumDecode(_$TtsProviderKindEnumMap, json['kind']),
  name: json['name'] as String? ?? '',
  enabled: json['enabled'] as bool? ?? false,
  apiKey: json['apiKey'] as String? ?? '',
  baseUrl: json['baseUrl'] as String? ?? '',
  model: json['model'] as String? ?? '',
  voice: json['voice'] as String? ?? '',
  groupId: json['groupId'] as String? ?? '',
  emotion: json['emotion'] as String? ?? '',
  speed: (json['speed'] as num?)?.toDouble() ?? 1.0,
  languageBoost: json['languageBoost'] as String? ?? '',
  sampleRate: (json['sampleRate'] as num?)?.toInt() ?? 32000,
  bitrate: (json['bitrate'] as num?)?.toInt() ?? 128000,
  audioFormat: json['audioFormat'] as String? ?? 'mp3',
  region: json['region'] as String? ?? '',
  azureRate: json['azureRate'] as String? ?? 'medium',
  azurePitch: json['azurePitch'] as String? ?? 'medium',
  azureVolume: json['azureVolume'] as String? ?? 'medium',
  azureStyle: json['azureStyle'] as String? ?? '',
  azureStyleDegree: (json['azureStyleDegree'] as num?)?.toDouble() ?? 1.0,
  azureRole: json['azureRole'] as String? ?? '',
  azureOutputFormat:
      json['azureOutputFormat'] as String? ??
      'audio-16khz-128kbitrate-mono-mp3',
  voiceName: json['voiceName'] as String? ?? '',
  stylePrompt: json['stylePrompt'] as String? ?? '',
  useMultiSpeaker: json['useMultiSpeaker'] as bool? ?? false,
  speaker1Name: json['speaker1Name'] as String? ?? '',
  speaker1Voice: json['speaker1Voice'] as String? ?? '',
  speaker2Name: json['speaker2Name'] as String? ?? '',
  speaker2Voice: json['speaker2Voice'] as String? ?? '',
  outputFormat: json['outputFormat'] as String? ?? '',
  stability: (json['stability'] as num?)?.toDouble() ?? 0.5,
  similarityBoost: (json['similarityBoost'] as num?)?.toDouble() ?? 0.75,
  elStyle: (json['elStyle'] as num?)?.toDouble() ?? 0.0,
  useSpeakerBoost: json['useSpeakerBoost'] as bool? ?? true,
  appId: json['appId'] as String? ?? '',
  cluster: json['cluster'] as String? ?? '',
  apiVersion: json['apiVersion'] as String? ?? 'auto',
  resourceId: json['resourceId'] as String? ?? '',
  volume: (json['volume'] as num?)?.toDouble() ?? 1.0,
  pitch: (json['pitch'] as num?)?.toDouble() ?? 1.0,
  encoding: json['encoding'] as String? ?? 'mp3',
  gain: (json['gain'] as num?)?.toDouble() ?? 0.0,
  maxTokens: (json['maxTokens'] as num?)?.toInt() ?? 1600,
  instructions: json['instructions'] as String? ?? '',
  mimoVoiceDescription: json['mimoVoiceDescription'] as String? ?? '',
  mimoOptimizeTextPreview: json['mimoOptimizeTextPreview'] as bool? ?? false,
  mimoVoiceCloneAudio: json['mimoVoiceCloneAudio'] as String? ?? '',
  qwenLanguageType: json['qwenLanguageType'] as String? ?? 'Auto',
  qwenInstructions: json['qwenInstructions'] as String? ?? '',
  qwenOptimizeInstructions: json['qwenOptimizeInstructions'] as bool? ?? false,
);

Map<String, dynamic> _$TtsProviderSettingToJson(_TtsProviderSetting instance) =>
    <String, dynamic>{
      'id': instance.id,
      'kind': _$TtsProviderKindEnumMap[instance.kind]!,
      'name': instance.name,
      'enabled': instance.enabled,
      'apiKey': instance.apiKey,
      'baseUrl': instance.baseUrl,
      'model': instance.model,
      'voice': instance.voice,
      'groupId': instance.groupId,
      'emotion': instance.emotion,
      'speed': instance.speed,
      'languageBoost': instance.languageBoost,
      'sampleRate': instance.sampleRate,
      'bitrate': instance.bitrate,
      'audioFormat': instance.audioFormat,
      'region': instance.region,
      'azureRate': instance.azureRate,
      'azurePitch': instance.azurePitch,
      'azureVolume': instance.azureVolume,
      'azureStyle': instance.azureStyle,
      'azureStyleDegree': instance.azureStyleDegree,
      'azureRole': instance.azureRole,
      'azureOutputFormat': instance.azureOutputFormat,
      'voiceName': instance.voiceName,
      'stylePrompt': instance.stylePrompt,
      'useMultiSpeaker': instance.useMultiSpeaker,
      'speaker1Name': instance.speaker1Name,
      'speaker1Voice': instance.speaker1Voice,
      'speaker2Name': instance.speaker2Name,
      'speaker2Voice': instance.speaker2Voice,
      'outputFormat': instance.outputFormat,
      'stability': instance.stability,
      'similarityBoost': instance.similarityBoost,
      'elStyle': instance.elStyle,
      'useSpeakerBoost': instance.useSpeakerBoost,
      'appId': instance.appId,
      'cluster': instance.cluster,
      'apiVersion': instance.apiVersion,
      'resourceId': instance.resourceId,
      'volume': instance.volume,
      'pitch': instance.pitch,
      'encoding': instance.encoding,
      'gain': instance.gain,
      'maxTokens': instance.maxTokens,
      'instructions': instance.instructions,
      'mimoVoiceDescription': instance.mimoVoiceDescription,
      'mimoOptimizeTextPreview': instance.mimoOptimizeTextPreview,
      'mimoVoiceCloneAudio': instance.mimoVoiceCloneAudio,
      'qwenLanguageType': instance.qwenLanguageType,
      'qwenInstructions': instance.qwenInstructions,
      'qwenOptimizeInstructions': instance.qwenOptimizeInstructions,
    };

const _$TtsProviderKindEnumMap = {
  TtsProviderKind.system: 'system',
  TtsProviderKind.openai: 'openai',
  TtsProviderKind.gemini: 'gemini',
  TtsProviderKind.minimax: 'minimax',
  TtsProviderKind.siliconflow: 'siliconflow',
  TtsProviderKind.azure: 'azure',
  TtsProviderKind.elevenlabs: 'elevenlabs',
  TtsProviderKind.volcano: 'volcano',
  TtsProviderKind.mimo: 'mimo',
  TtsProviderKind.qwen: 'qwen',
};
